### ISSUE TITLE
how to add cuda library

### ISSUE THREAD

**Issue by neha-22** [WeisongZhao/AdaptiveOptics.simulation#2]
i am working on matlab trial version. Is it possible to run this code free.

**Comment by WeisongZhao** [comment]
Certainly, if I understand you correctly.

**Comment by neha-22** [comment]
can we run this code without using cuda

**Comment by WeisongZhao** [comment]
Yes, you can remove all the `gpuArray` function.

**Comment by neha-22** [comment]
thank you so much.
Sorry to disturb you again.
I need your guidance. please suggest what to do in this field

**Comment by neha-22** [comment]
it is not running after removing the gpuarray function.
How long it will take to run.
